# Generated by Django 3.1.7 on 2021-02-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superhog_app', '0004_externalfileinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='gallery',
            field=models.ManyToManyField(to='superhog_app.ExternalFileInfo'),
        ),
    ]
