# Generated by Django 3.1.7 on 2021-02-22 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superhog_app', '0005_article_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_type',
            field=models.SmallIntegerField(choices=[(0, 'Superhog różne'), (1, 'Superhog rozgrywka'), (2, 'Superhog potwory'), (3, 'Superhog kod źródłowy'), (10, 'Inne programy')], default=0),
        ),
        migrations.AlterField(
            model_name='externalfileinfo',
            name='filetype',
            field=models.SmallIntegerField(choices=[(0, 'Picture'), (1, 'Video'), (2, 'Text'), (3, 'Source code'), (4, 'Other')], default=0),
        ),
    ]
