# Generated by Django 3.1.7 on 2021-02-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superhog_app', '0007_auto_20210223_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='gallery',
            field=models.ManyToManyField(to='superhog_app.ExternalFileInfo'),
        ),
    ]
