# Generated by Django 3.0.10 on 2021-03-31 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superhog_app', '0008_auto_20210223_0744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genus', models.CharField(max_length=30)),
                ('species', models.CharField(max_length=30)),
                ('feed', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
    ]
